name: bug-report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: どんな不具合が出る？
    placeholder: Tell us what you see!
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: どんな動作を期待していた？
    placeholder: Tell us what you expected!
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: 不具合の再現方法
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? Reference? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
