name: 🖊Feature request
description: File a feature request
title: "[New Feature]: "
labels: ["enhancement"]
body:
- type: textarea
  attributes:
    label: Feature Request
    description: 欲しい機能はなに？
    placeholder: Tell us what you want!
  validations:
    required: true
- type: textarea
  attributes:
    label: Reason For Request
    description: なぜその機能が欲しい？
    placeholder: Tell us why you want!
  validations:
    required: true
- type: textarea
  attributes:
    label: Implementation Method
    description: 実装方法
    placeholder: |
      1. Replacing class component...
      2. Enhance the css...
      3. Polish up the algorithm... 
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? Reference? Anything that will give us more context about the feature request!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
